# Configuración de base de datos MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/medicronos?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=7200787Sapo!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración del servidor web
server.port=8080
